apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress-cookie
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "MY_CUSTOM_ID"
    nginx.ingress.kubernetes.io/session-cookie-expires: "3600"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cookie-service
            port:
              number: 80
